name: Build Workflow

on:
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Loading repository
        uses: actions/checkout@v2

      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build --if-present

      - name: Running Tests
        run: npm run test

      - name: Upload code coverage
        uses: actions/upload-artifact@v2
        with:
          name: codecoverage
          path: |
            coverage

      - name: Upload dist
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: |
            dist
            !*.original.html

  analysis:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Loading repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Loading code coverage
        uses: actions/download-artifact@v2
        with:
          name: codecoverage
          path: |
            coverage

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}